### ISSUE TITLE
UnconstrainedEndPoseProblem has unused Goal; ik_solver doesn't use it

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#128]
As discussed

**Comment by VladimirIvan** [comment]
```UnconstrainedEndPoseProblemInitializer``` has a ```Goal``` parameter that is used to initialize ```UnconstrainedEndPoseProblem.y```. This is then used in IK solver.

I couldn't find any unused ```Goal``` variables. I think we may have not understood each other entirely in the chat.

**Comment by wxmerkt** [comment]
Okay, makes sense.
