### ISSUE TITLE
Calculated distance points for meshes wrong for large triangles

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#153]
This is most likely an issue with FCL or the way we are pushing meshes from the MoveIt planning scene to FCL (visually, the faces do not show up). The CollisionProxy does not point to the closest point...

![image](https://user-images.githubusercontent.com/1664508/31628883-dc36dc7a-b2a9-11e7-8652-e460554060ea.png)

**Comment by wxmerkt** [comment]
Actually, this worked better with the old FCL before the big CollisionScene re-shuffling

**Comment by VladimirIvan** [comment]
I've seen this issue with shape primitives as well. I switched to the ```fcl::GST_INDEP``` solver to fix it. That may not be a good solver for meshes?
Do small triangles work fine?

**Comment by wxmerkt** [comment]
This has been fixed in #159 as well:

![image](https://user-images.githubusercontent.com/1664508/31691109-c9667d92-b38c-11e7-91aa-e3af78614613.png)
