### ISSUE TITLE
Collision Checking with Meshes Broken

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#155]
Just noticed that with the new collision scene OMPL is broken for a scene with meshes (the same I have been using for weeks) - i.e. RRT plans a straight line through the mesh as if it wasn't there. This essentially breaks all our collision checking against meshes.

Even for the normal IK scene when I visually cannot see any collision in neither the planning scene nor the published collision shapes it returns 943 collision proxies with ~650 being closer than a centimetre.

This is a more general case of #153 - not only the points are wrong, the entire collision check is broken (both for old and new FCL).

**Comment by wxmerkt** [comment]
Actually, how is this even possible?

```
Proxy: 'leftKneePitchLink_collision_0' - 'rightHipPitchLink_collision_0', c1: 0.442919 0.337705 0.398604 c1:   0.24 0.0984 0.7788 d: 0
```

for:

![image](https://user-images.githubusercontent.com/1664508/31638761-3dbe90aa-b2cd-11e7-8da4-3382dff5b44d.png)

**Comment by VladimirIvan** [comment]
I didn't test this with meshes.
FCL issues and PRs would suggest that not all their algorithms are fully implemented for all shapes yet. Check if ```fcl::GST_LIBCCD``` and ```fcl::GST_INDEP``` have the same issue.
