### ISSUE TITLE
Collision Proxies returned for pairs that are disabled in ACM

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#156]
Is that by design?

**Comment by VladimirIvan** [comment]
The overload of ```getCollisionDistance``` that takes the names of the links does not check for ACM because you specifically requested the links. You can add it as a optional feature if you need it.
The other one does check for ACM.

**Comment by wxmerkt** [comment]
Verified this is a bug:

![image](https://user-images.githubusercontent.com/1664508/31671609-3dcda290-b352-11e7-8ba6-080b7f74f4f4.png)

**Comment by wxmerkt** [comment]
After switching to INDEP per #159 we get some really wild CollisionProxies in an otherwise empty scene:

![image](https://user-images.githubusercontent.com/1664508/31679728-ed63e856-b369-11e7-98da-4fa0789f13c9.png)
