### ISSUE TITLE
Contact points for collision between primitive shape and mesh wrong

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#184]
This is the proxy for the closest distance between the red hip yaw link sphere and the torso yaw link mesh:

![image](https://user-images.githubusercontent.com/1664508/32368637-53a59d5a-c07e-11e7-8d91-8f45401c1884.png)

**Note:** This is the proxy being returned (distance seems correct):
```
Proxy: 'torsoYawLink_collision_0' - 'rightHipYawLink_collision_0', c1:          0 -0.0228953 -0.0911919 c1:          0 -0.0258317    0.92829 d: 0.00625062
```

**Comment by VladimirIvan** [comment]
Could this be another local/global frame inconsistency based on colliding shape type?

**Comment by wxmerkt** [comment]
Definitely, is a more complicated issue stemming from FCL. The contact points also change when swapping the order of e1 and e2, i.e. they are different for whether the primitive or the mesh is the first pair in the collision query.

I managed to fix and verify the contact points for most cases bar one. For primitive vs mesh I will add a work-around flipping the order internally.

###  Primitive vs Primitive: OK with INDEP, broken with LIBCCD
#### LIBCCD: broken
![image](https://user-images.githubusercontent.com/1664508/32407948-faddd92a-c187-11e7-8762-ce18af845c43.png)

#### INDEP: OK
![image](https://user-images.githubusercontent.com/1664508/32407950-05988162-c188-11e7-8ede-f693535044f2.png)

### Mesh vs Mesh: OK (with either INDEP and LIBCCD)
![image](https://user-images.githubusercontent.com/1664508/32407936-cc96072c-c187-11e7-97f5-8fca5a53a2eb.png)

### Primitive vs Mesh: BROKEN
![image](https://user-images.githubusercontent.com/1664508/32407970-6e8eed5a-c188-11e7-8950-9dfc1cd69644.png)


### Mesh vs Primitive: OK (with either INDEP and LIBCCD)
![image](https://user-images.githubusercontent.com/1664508/32407967-4ea2d31c-c188-11e7-9079-344d8c3c09d2.png)


Aside, I found the following notes in the FCL code:
1. It is noted that INDEP is known not being able to compute the nearest points properly and we should rely on LIBCCD for that, cf. [here](https://github.com/flexible-collision-library/fcl/blob/master/test/test_fcl_signed_distance.cpp#L85-L86). I could not fully confirm that in my primitive-sphere vs primitive-mesh test and results were the same.
2. The nearest points are not guaranteed to lie on the surface of the objects when penetrating, cf. [here](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/distance-inl.h#L184-L185).
3. For meshes and octree it's not guaranteed to be on the surface of the object, cf. [here](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/distance-inl.h#L140-L146).

**Comment by wxmerkt** [comment]
After more investigation we now need to consider 16 (!) different cases:

The four major pairs:

1. Primitive vs Primitive
2. Mesh vs Mesh
3. Primitive vs Mesh
4. Mesh vs Primitive

Two solvers:

1. INDEP
2. LIBCCD

Two main conditions:

1. In contact, i.e. closest distance < 0
2. Not in contact, i.e. closest distance > 0

And again each of these combinations comes with a different frame convention that needs to be respected when converting collision check results to global/world frame. I added a new commit implementing this in #190 and tested it on a complex concave (!) mesh vs primitive shapes and other complex concave meshes.
