### ISSUE TITLE
Add/expose update count for problems

### ISSUE THREAD

**Issue by VladimirIvan** [ipab-slmc/exotica#226]
- Add update count to the scene.
- Add python wrapper.

This is a critical feature for benchmarking. It use to exist but it got lost during restructuring of the problem/scene.

**Comment by wxmerkt** [comment]
Is the scene or problem update count relevant? ``resetNumberOfProblemUpdates`` and ``getNumberOfProblemUpdates`` exist in the planning problem and are wrapped - it's what I use to get updates

**Comment by VladimirIvan** [comment]
Grand. Quickest issue ever.
