### ISSUE TITLE
Expose the LazyPRM OMPL planner in python

### ISSUE THREAD

**Issue by rfishy1** [ipab-slmc/exotica#239]
The [OMPL LazyPRM planner](http://ompl.kavrakilab.org/classompl_1_1geometric_1_1LazyPRM.html#gLazyPRM) is not exposed in the python bindings for EXOTica.

Expanding the selection of exposed planners would improve the usefulness of EXOTica for benchmarking planning algorithms.

**Comment by VladimirIvan** [comment]
I have added the LazyPRM but it's not able to solve even the sample problem. I don't think the OMPL implementation is working or we are missing a step in the planner setup.

@rfishy1 Have a look at 78b808f but I don't see an easy fix.

**Comment by rfishy1** [comment]
@VladimirIvan Occasionally the solver works (about half the time for the example script), and uses between 1000 and 4000 problem updates. 

It seems that the ten second timeout is usually insufficient to solve the task (for a successful attempt). The image below has the solve times for the 10 loop iterations. It seems that once a path is found, the roadmap is retained and reused. I'll look at the setup to see whether there's a step which would improve the performance.

![kazam_screenshot_00006](https://user-images.githubusercontent.com/12380477/35765780-b811ce6a-08d3-11e8-8fee-f1218f7672c3.png)

**Comment by VladimirIvan** [comment]
I'll increase the the timeout in the example to 10s and merge then.
