### ISSUE TITLE
Re-add moveit_msgs/RobotState publishing

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#248]
Action from today's meeting as mentioned by @cam586 and @cmower 

Requires:

- Collecting environment objects (currently published as CollisionShapes)
- Robot State as JointState

**Comment by VladimirIvan** [comment]
The display of the robot state using the `JointState` and a joint state publisher was just a temporary solution to display exotica states for debugging. This has been now replaced with publishing TFs directly. This is faster, it allows to debug problems with kinematics, and it also publishes frames for scene objects.

Joint state messages can still be published by the node running exotica, if the application requires it.

The examples/tutorials should be updated to reflect this. Good job spotting this.
Action: updated example code and documentation.
