### ISSUE TITLE
AICO: Add tolerances

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#256]
AICO currently doesn't have any exit criteria beyond Change-tolerance-in-x-between-iterations (Tolerance) and maximum iterations. We should add gradient and function tolerance.  

This is a good reference for definitions (absolute and relative): https://uk.mathworks.com/help/optim/ug/tolerances-and-stopping-criteria.html

and

https://uk.mathworks.com/help/optim/ug/first-order-optimality-measure.html

**Comment by VladimirIvan** [comment]
Tolerance in the task space is easy to add. Gradient may be trickier. I'm open to suggestions how to compute this.

**Comment by wxmerkt** [comment]
- Function tolerance is ``(cost_old-cost)<ftol`` (also called relative tolerance).
- Absolute tolerance is ``cost < abstol``

I'll add them the next time I update my scripts.
