### ISSUE TITLE
Change trajectories from vector to matrix in TimeIndexedProblems

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#262]
Trajectories are currently a vector of vectors - in order to compute some optimality and convergence criteria (as well as use of differentiation matrices etc.) it's better if they are matrices.

I'll convert this in March and this issue is to keep track.

**Comment by VladimirIvan** [comment]
When implementing this, make sure that column and row vectors and sub-vectors (row(), col(), block(), ...) are passed correctly as function arguments. Eigen does not handle row-to-column-major conversion implicitly when using the Ref class.
