### ISSUE TITLE
Allow relaxation/different weighting of individual taskmap dimensions

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#305]
E.g. for orientation to have different weighting on roll/pitch/yaw (or even zero for some).

cc @cmower 

Related:

- https://github.com/ipab-slmc/exotica/blob/master/exotica/src/Tasks.cpp#L118-L128

**Comment by VladimirIvan** [comment]
We used to have this feature but it got never used got deprecated.
EffFrame TaskMap can be split into EffOrientation and EffPosition and weighted with Rho to achieve this.

**Comment by wxmerkt** [comment]
This got superseeded by adding new task maps.
