### ISSUE TITLE
SNOPT Derivative Checking throws on our orientation derivatives

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#334]
When turning derivative verification in SNOPT on it fails if using any of our orientation task maps. Using any other task map works. Our own finite differencing tests pass, but fail when increasing the ``eps`` even on position (which passes with SNOPT).

**Comment by VladimirIvan** [comment]
I reduced the `eps` in the orientation tests in #402.
We may want to re-check this after fixes added in #406, #407, #408 and #409.
If the issue still exists, I suspect the KDL based FK/Jacobian being the cause of this since there should be no other code affecting that computation.
