### ISSUE TITLE
exo.Setup.initRos() blocks SIGINT (Ctrl+C)

### ISSUE THREAD

**Issue by christian-rauch** [ipab-slmc/exotica#340]
When using `exo.Setup.initRos()` (in python) I am unable to terminate the process via `Ctrl+C`, respectively `kill -s SIGINT <pid>`.

**Comment by VladimirIvan** [comment]
Do the examples terminate?
Eg. `roslaunch exotica_examples PythonPlanIK.launch`

**Comment by christian-rauch** [comment]
I checked `example_ik.py` which seems to solve the problem by registering its own signal handler via: `signal.signal(signal.SIGINT, sigIntHandler)`. After removing this signal handler, I observe the same behaviour (blocking with `initRos()`).

**Comment by christian-rauch** [comment]
Is this a limitation for the Python wrapper only? I imageine registering a signal handler in the library (C++) it should do the same.
Do you know where the SIGINT is going? I think each process has a default handler unless its redefined. Is it catched and ignored by ROS?

**Comment by VladimirIvan** [comment]
This is python behaviour only.
I believe that c++ handles this as an exception.
