### ISSUE TITLE
Usage of callback in Scene::requestKinematics

### ISSUE THREAD

**Issue by christian-rauch** [ipab-slmc/exotica#359]
Why is `Scene::requestKinematics`: https://github.com/ipab-slmc/exotica/blob/5d7a273a662f0e60b157b031a61fb4ddf75db44a/exotica/src/Scene.cpp#L179-L186
using a callback instead of directly returning the `kinematicSolution`?

It seems that `kinematica_.RequestFrames` is processed synchronously, so `requestKinematics` will always return only after `callback` got called.

**Comment by VladimirIvan** [comment]
When the scene gets updated, TaskMaps have to be updated to receive the correct pointers to the kinematic solutions. The callback is used for that.
