### ISSUE TITLE
Implementation of PseudoInverse

### ISSUE THREAD

**Issue by christian-rauch** [ipab-slmc/exotica#391]
Which algorithm is the basis for `IKsolver::PseudoInverse`?

In the configuration J.cols() < J.rows() and C==0 the pseudo inverse is computed as:
```C++
Jpinv = inverseSymPosDef(J.transpose() * J + W) * J.transpose();
```

For  W=I (identity) is this supposed to provide the same result as the Moore-Penrose pseudoinverse?

I have a case where `IKsolver` gives me quite small update steps (q_d) for a sparse Jacobian, while Matlab's `pinv()` seems to provide the correct q_d.

**Comment by christian-rauch** [comment]
Relacing 
```C++
Eigen::MatrixXd Jinv = PseudoInverse(prob_->Cost.S * prob_->Cost.J);
```
with 
```C++
Eigen::MatrixXd Jinv = (prob_->Cost.S*prob_->Cost.J).completeOrthogonalDecomposition().pseudoInverse();
```
already gives me a faster convergence.
How would I need to set `C` and `W` to obtain the same pseudo inverse from `IKsolver::PseudoInverse` as provided by Eigen and Matlab?

**Comment by christian-rauch** [comment]
Quick update: I implemented the Gauss-Newton (actually Levenberg-Marquardt) solver https://github.com/christian-rauch/gauss_newton_exo_solver to compare the convergence on a synthetic case. In the case shown, I am adding links iteratively to the set of optimised links, but this should not matter. Optimisation for 5 x 5 iterations:

Inverse Kinematics (IK):
![exo_ik](https://user-images.githubusercontent.com/8226248/47926880-af875c80-deb9-11e8-91ca-dd62b763fe2b.gif)

Levenberg-Marquardt (LM):
![exo_lm](https://user-images.githubusercontent.com/8226248/47926895-bf06a580-deb9-11e8-82e5-a5886f316da0.gif)

The LM is using an adaptive damping factor with damping direction depending on the Hessian approximation as described here: https://uk.mathworks.com/help/optim/ug/least-squares-model-fitting-algorithms.html

**Comment by VladimirIvan** [comment]
Thanks for pointing out the problems with the IK solver. I'll have a look at it and fix it.

I really like your minimal LM implementation. I'd love to add it to the core exotica.
