### ISSUE TITLE
Planning example for AICO with collision avoidance

### ISSUE THREAD

**Issue by teguhSL** [ipab-slmc/exotica#396]
Hi, I am trying to use AICO to plan a trajectory for LWR while avoiding collision. I tried to follow the examples provided, but the only ones that I can find are for the time indexed sampling problem. 

In the documentation I can only find Sphere and SphereCollision for task maps to check for collision. Does it mean that I have to define a sphere for each link and object, and then define a SphereCollision map for each pair? And if yes, how should I determine the location and the size of the spheres?

It would be very helpful if there is one working example using AICO and collision avoidance.

Thank you!
@VladimirIvan

**Comment by VladimirIvan** [comment]
I'll look into writing an example.

> Does it mean that I have to define a sphere for each link and object, and then define a SphereCollision map for each pair? And if yes, how should I determine the location and the size of the spheres?

Yes. There is an extension of the `Frame` initialiser (`Sphere`) that adds radius and collision group. The additional parameters will be parsed correctly in the background. The full task map should look like this (untested):
```
<SphereCollision Name="Collision">
           <Precision>0.01</Precision>
           <ReferenceFrame>/world</ReferenceFrame>
           <EndEffector>
                       <Frame Link="base" Radius="0.3" Base="Target" Group="base" />
                       <Frame Link="endeff" Radius="0.3" Base="Target" Group="eff" />
           </EndEffector>
</SphereCollision>
``` 
The cost is sigmoidal and the `Precision` parameter sets how steep it is (0.01 = 1cm ramp up from 0 to 1). `ReferenceFrame` is used only for publishing TF/markers for debugging. Only spheres in different collision groups will be checked. The group name can be an arbitrary string.

There is a test in [test_maps.cpp](https://github.com/ipab-slmc/exotica/blob/aebce9c118bea7155cec35c282b304afe79bfd13/examples/exotica_examples/tests/test_maps.cpp#L373) but it doesn't use XML for initialisation so it may be harder to read.
