### ISSUE TITLE
Random crashes related to memory allocation/deallocation

### ISSUE THREAD

**Issue by christian-rauch** [ipab-slmc/exotica#459]
Since recently I am getting crashes related to memory allocation/deallocation.

With the recent master 1ac88790f32e90e2d564d25392b5b7c8fa22e9a6 (`[exotica_examples] Use damping in LM example`) I am getting random crashes with varying backtraces:
- https://pastebin.com/dDDEi35V
- https://pastebin.com/vi1rQEwG
- https://pastebin.com/EGE4nP21
- https://pastebin.com/WY7DvQ1n

These crashes did not appear with db89e6fe27b97884fb918faf0d4d9c367cdf6496 (`rename parameter 'self' to 'check_self_collision'`).

I will do some bifurcation searched to find the commit that causes these crashes.

**Comment by christian-rauch** [comment]
It seems that commit e612bbb9328b5a8beeee25711eeb2cd644738b53 (keep global list of published collision shapes) caused the issues.
The issue does not appear, if `publishFrames` is not called.

**Comment by wxmerkt** [comment]
Should have been fixed in #445 - if not please reopen.
