### ISSUE TITLE
Quaternion coefficient order

### ISSUE THREAD

**Issue by christian-rauch** [ipab-slmc/exotica#488]
EXOTica is currently using the Quaternion coefficient order: x, y, z, w. I.e. imaginary part (vector (x,y,z)) first, real part (scalar w) second.

There seems to be no proper definition of the order of real and imaginary part for Quaternions.

Use of order wxyz:
- in the domain of imaginary numbers, the real part comes before the imaginary part
- `Robotics. Modelling, Planning and Control` (B. Sicilliano), section 2.6 (Unit Quaternion) uses q = (scalar, vector)
- wikipedia uses (w,x,y,z)
- Drake uses w,x,y,z
- Matlab uses w,x,y,z
- `Eigen::Quaternion` constructor uses (w,x,y,z)
- most important: Sethu uses wxyz in RSS :-)

Use of order xyzw:
- `Eigen::Quaternion` stores internally in order (x,y,z,w)
- `KDL::Quaternion` is constructed in order x,y,z,w
- ROS TF python conversion library (3rd party) uses xyzw

I consider the order w,x,y,z the proper Quaternion order since it is used in this order in major textbooks, references and libraries in this domain.

I would like EXOTica to use the same coefficient order.
What was the original reason to use xyzw and are you willing to change it to textbook order wxyz?

**Comment by VladimirIvan** [comment]
The reason were precisely the three main libraries used in ROS (KDL, TF, and Eigen). Most other places in ROS (messages, rviz, OGRE, ...) also use xyzw. I think I avoided ever using the `Eigen::Quaternion(w,x,y,z)`, hence no problem there. I quite like that the Eigen Quaternion to 4d vector can use the existing order coefficients out of the box.

We had some issues with Drake in the past so we had to reorder.

I'd avoid changing the convention unless we switch to a whole different underlying kinematic library (abandon KDL). 

>> most important: Sethu uses wxyz in RSS :-)

Sethu also calls it the quarternion ;)
