### ISSUE TITLE
exotica_python: Numpy array vs matrix

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#593]
Our Python wrapper returns ``numpy.array``. However, many times that breaks the shape of vectors or just makes it hard to get the correct matrix operations (it's easy to end up with incorrect operations). 

It would be better to return ``numpy.matrix``. On a quick search I haven't found a solution with pybind11 yet, but we should investigate this in the future.

**Comment by jcarpent** [comment]
[EigenPy](https://github.com/stack-of-tasks/eigenpy) may help you at this stage. We support both, and you can switch the conversion online.

**Comment by wxmerkt** [comment]
Thank you Justin :-) We'd like to retain pybind11 and avoid boost-python. I didn't see a way to do this with EigenPy, but may have missed it?

**Comment by jcarpent** [comment]
I do understand your choice. In our context, we use the following lines to perform the switch:
```
import eigenpy
eigenpy.switchToNumpyArray()
```

**Comment by wxmerkt** [comment]
[`np.asmatrix`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.asmatrix.html) is the solution of choice (which does not make a copy) until we find a way to switch within pybind11, which likely requires a fix to it.
