### ISSUE TITLE
Issue with EffAxisAlignment and manual initialization

### ISSUE THREAD

**Issue by cmower** [ipab-slmc/exotica#608]
I have an `.xml` with task map defined as follows
```xml
<EffAxisAlignment Name="Direction">
  <EndEffector>
    <Frame Link="EffFrame" Base="WallFrame" Axis="0 0 1" Direction="0 0 1"/>
  </EndEffector>
</EffAxisAlignment>
```
where `WallFrame` is some arbitrary frame defined wrt to the world frame. My goal is to define a task that aligns the z-axis of the end-effector with the z-axis of the wall frame within an `UnconstrainedEndPoseProblem` and an `EndPoseProblem`.

Loading `myconfig.xml` in the following way throws the following flags. 

```python
>>> import pyexotica as exo
>>> xml='myconfig.xml'
>>> sol_gen, pr_gen = exo.Initializers.load_xml_full(xml)
>>> pr = exo.Initializers.Initializer(pr_gen)
[EXOTica]: exotica/Frame: Ignoring property 'Direction'
[EXOTica]: exotica/Frame: Ignoring property 'Axis'
```

I tried changing the `.xml`to 
```xml
<EffAxisAlignment Name="Direction">
  <EndEffector>
    <FrameWithAxisAndDirection Link="EffFrame" Base="WallFrame" Axis="0 0 1" Direction="0 0 1"/>
  </EndEffector>
</EffAxisAlignment>
```
but got this output instead
```python
>>> import pyexotica as exo
>>> xml='myconfig.xml'
>>> sol_gen, pr_gen = exo.Initializers.load_xml_full(xml)
>>> pr = exo.Initializers.Initializer(pr_gen)
[EXOTica]: exotica/FrameWithAxisAndDirection: Ignoring property 'Base'
[EXOTica]: exotica/FrameWithAxisAndDirection: Ignoring property 'Link'
```
In both cases the solver, when created using the following, gives outputs.
```python
>>> problem = exo.Setup.create_problem(pr)
[ INFO] [1561546907.821029813]: Loading robot model 'lwr'...
>>> solver = exo.Setup.create_solver(sol)
>>> solver.specify_problem(problem)
>>> solver.solve()
array([[  1.60605007e+00,  -8.09905674e-01,   6.30626153e-03,
         -2.09743747e-01,  -9.97217735e-02,  -7.89833017e-01,
         -9.61911102e-16]])
```
However upon inspection the alignment task is clearly not being enforced.

When running the `exotica_examples` script for `EffAxisAlignment` all works as expected, however here the example `.xml` config is not being processed through `exotica_python` so my guess is that the problem stems from the initialization process in `pyexotica.cpp` and perhaps has something to do with eb26a0ad4982e5d14ef89e0b72afb29db61c90d6 but I am at a loss of how to fix.

**Comment by wxmerkt** [comment]
Thank you for raising this - turns out I extended the wrong intializer in `EffAxisAlignment`, yet, surprisingly so, it worked in C++ due to the explicit instantiation:

https://github.com/ipab-slmc/exotica/blob/eb26a0ad4982e5d14ef89e0b72afb29db61c90d6/exotations/exotica_core_task_maps/src/eff_axis_alignment.cpp#L53

which is the same as for `SphereCollision`

https://github.com/ipab-slmc/exotica/blob/eb26a0ad4982e5d14ef89e0b72afb29db61c90d6/exotations/exotica_core_task_maps/src/sphere_collision.cpp#L45

#609 fixes the issue.
