### ISSUE TITLE
Non-deterministic roll-outs in iLQG example

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#613]
Running `rosrun exotica_examples example_dynamic_time_indexed 10` results in vastly different (read unstable) roll-outs despite using the feedback gains - the first two are essentially the same, the third is... unstable.

**Comment by include4eto** [comment]
Why is this an issue? Isn't that what (velocity) noise is supposed to look like? I'll look into it to make sure there aren't any mistakes, but it looks OK to me. Note I'm not seeding the generator, so it should always be the same (random) roll-outs.

**Comment by wxmerkt** [comment]
When using the feedback control policy, I do expect some determinism - or is the noise perhaps set too large?

**Comment by include4eto** [comment]
https://github.com/ipab-slmc/exotica/pull/656
