### ISSUE TITLE
Convergence checks in dynamics solvers.

### ISSUE THREAD

**Issue by include4eto** [ipab-slmc/exotica#640]
Sometimes states become `NaN`. Add checks to stop iteration and return no solution.

**Comment by wxmerkt** [comment]
`allFinite()` is your friend

**Comment by include4eto** [comment]
Add `terminationcriterion` to python and use it.

**Comment by include4eto** [comment]
https://github.com/ipab-slmc/exotica/pull/637

**Comment by include4eto** [comment]
This was added in https://github.com/ipab-slmc/exotica/pull/637 .
