### ISSUE TITLE
Fix header-only implementation of AbstractDDPSolver and OMPLControlSolver

### ISSUE THREAD

**Issue by include4eto** [ipab-slmc/exotica#644]
`libraryunload` poco exceptions when having the implementation for a base class in a separate `.cpp` file. `AbstractDDPSolver` and `OMPLControlSolver` suffer from it and therefore need to have the implementation in the header file.

@VladimirIvan The other OMPL solver seems to make this work.

TODO: I don't know how or why OMPL solver doesn't suffer from this.

**Comment by include4eto** [comment]
See `template class OMPLSolver<SamplingProblem>;` and use 
`planner_allocator_ = boost::bind(&AllocatePlanner<ompl::geometric::LBTRRT>, _1, _2);`-like syntax.

**Comment by wxmerkt** [comment]
I think you need to have the template class fully instantiated. Look at the `AbstractTimeIndexedProblem` for an example.

**Comment by include4eto** [comment]
Fixed in https://github.com/ipab-slmc/exotica/pull/652
