### ISSUE TITLE
DDP, iLQG solvers return wrong-sized solution

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#654]
If the problem horizon is `T`, then:

- `X` is of size `T`
- `U` is of size `T-1`
- The `solution` in `Solve` in the solvers is **resized** to `T` without initialising or reinitialising to 0. At the end of solve, only the T-1th rows are getting set from the best U. That returns an additional row with a wrongly initialised memory.

Two possible solutions:
a) The returned solution should be of size `T-1`
b) The final command should be a hold/inverse dynamics solution or zeros. 

I tend to (a).

**Comment by include4eto** [comment]
So the issue is this line here: https://github.com/ipab-slmc/exotica/blob/3462afd9928c02989754de09229f7ea6daebea23/exotations/solvers/exotica_ddp_solver/src/abstract_ddp_solver.cpp#L61

The solution is resized to `T`, not to `T - 1`, which is the issue (in the first paragraph you said `T-1`).

**Comment by include4eto** [comment]
https://github.com/ipab-slmc/exotica/pull/656
