### ISSUE TITLE
Support for differential drive robots

### ISSUE THREAD

**Issue by maxspahn** [ipab-slmc/exotica#701]
Currently, it is possible to plan with floating bases. Libraries like OMPL also support differential drives, using DubinsStateSpaces or ReedsSheppStateSpaces. Integrating this feature would allow planning for a new range of robots, mainly autonomous cars and mobile manipulators.

**Comment by wxmerkt** [comment]
Hi @maxspahn,
Thank you for using Exotica. With the new motion problems using dynamics (`DynamicTimeIndexedShootingProblem`) and corresponding solvers, this can be realised by creating a new `DynamicsSolver`.

What is your application and intended use? Mostly sampling- or optimisation-based planning? Also happy for you to drop me an email (wolfgang at robots.ox.ac.uk) if you'd like to discuss in private.

Best wishes,
Wolfgang
