### ISSUE TITLE
CollisionSceneFCL won't work on Noetic

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#725]
The ROS community recently decided to manually package FCL 0.6 for ROS Noetic. This means that `exotica_collision_scene_fcl` (the default, FCL 0.5 one) will no longer work.

We need to decide if it makes sense removing it entirely (making `exotica_collision_scene_fcl_latest` the default - with the `fcl_catkin` packaged FCL) or to branch and disable it on 20.04.

**Comment by VladimirIvan** [comment]
I'd vote for using the latests by default and removing the system one. I don't think there were missing features (quite the opposite) and it seems to resolve the issue with minimal work needed.
