### ISSUE TITLE
Is position only IK possible?

### ISSUE THREAD

**Issue by RVSagar** [ipab-slmc/exotica#751]
Hi There,

I have a problem where I've setup some task maps and am solving IK queries. Is it possible to do a position only IK query? i.e., find a solution that achieves the position [x, y, z] with any orientation? I saw that if I pass in a query pose that is not of length 6 [x, y, z, r, p, yaw], an error is thrown, so I was wondering if there is any other way to achieve this.

Currently I'm doing something like this, where `left_arm_pose` is of length 6, but this requires me to explicitly set the orientation.

```python
self.exotica_ik_solver.get_problem().set_goal('LeftArm', left_arm_pose)
```

Thanks for your help!

**Comment by wxmerkt** [comment]
If you change `EffFrame` to `EffPosition` in the XML, it will solve for exactly that

**Comment by RVSagar** [comment]
Thank you, that totally slipped my mind, appreciate your response :), I will close this now
